"""Update AIPrediction for current-state baseline

Revision ID: 39c92feb0679
Revises: b61f560639ca
Create Date: 2026-09-02 10:46:19.812768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c92feb0679'
down_revision: Union[str, Sequence[str], None] = 'b61f560639ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_predictions', sa.Column('prediction_type', sa.String(), nullable=True))
    op.add_column('ai_predictions', sa.Column('predicted_class', sa.Integer(), nullable=False))
    op.add_column('ai_predictions', sa.Column('mastitis_probability', sa.Float(), nullable=False))
    op.add_column('ai_predictions', sa.Column('model_name', sa.String(), nullable=False))
    op.add_column('ai_predictions', sa.Column('features_used', sa.String(), nullable=True))
    op.drop_column('ai_predictions', 'risk_factors')
    op.drop_column('ai_predictions', 'risk_level')
    op.drop_column('ai_predictions', 'days_to_onset')
    op.drop_column('ai_predictions', 'probability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_predictions', sa.Column('probability', sa.FLOAT(), nullable=False))
    op.add_column('ai_predictions', sa.Column('days_to_onset', sa.INTEGER(), nullable=True))
    op.add_column('ai_predictions', sa.Column('risk_level', sa.VARCHAR(), nullable=False))
    op.add_column('ai_predictions', sa.Column('risk_factors', sa.VARCHAR(), nullable=True))
    op.drop_column('ai_predictions', 'features_used')
    op.drop_column('ai_predictions', 'model_name')
    op.drop_column('ai_predictions', 'mastitis_probability')
    op.drop_column('ai_predictions', 'predicted_class')
    op.drop_column('ai_predictions', 'prediction_type')
    # ### end Alembic commands ###
