"""Add settings fields

Revision ID: 3d8999a42358
Revises: 44c24b97ccbb
Create Date: 2026-09-02 22:08:27.526721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8999a42358'
down_revision: Union[str, Sequence[str], None] = '44c24b97ccbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('vet_name', sa.String(), nullable=True))
    op.add_column('farms', sa.Column('vet_phone', sa.String(), nullable=True))
    op.add_column('farms', sa.Column('vet_email', sa.String(), nullable=True))
    op.add_column('farms', sa.Column('additional_details', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    op.drop_column('farms', 'additional_details')
    op.drop_column('farms', 'vet_email')
    op.drop_column('farms', 'vet_phone')
    op.drop_column('farms', 'vet_name')
    # ### end Alembic commands ###
