"""Add Wokwi sensor fields

Revision ID: 44c24b97ccbb
Revises: 90fbed9f27c6
Create Date: 2026-09-02 13:04:35.093816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c24b97ccbb'
down_revision: Union[str, Sequence[str], None] = '90fbed9f27c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collar_readings', sa.Column('acceleration_magnitude', sa.Float(), nullable=True))
    op.add_column('collar_readings', sa.Column('rumination_sound_level', sa.Float(), nullable=True))
    op.add_column('collar_readings', sa.Column('humidity', sa.Float(), nullable=True))
    op.add_column('milk_readings', sa.Column('spectral_f1', sa.Float(), nullable=True))
    op.add_column('milk_readings', sa.Column('spectral_f2', sa.Float(), nullable=True))
    op.add_column('milk_readings', sa.Column('spectral_f3', sa.Float(), nullable=True))
    op.add_column('milk_readings', sa.Column('spectral_f4', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milk_readings', 'spectral_f4')
    op.drop_column('milk_readings', 'spectral_f3')
    op.drop_column('milk_readings', 'spectral_f2')
    op.drop_column('milk_readings', 'spectral_f1')
    op.drop_column('collar_readings', 'humidity')
    op.drop_column('collar_readings', 'rumination_sound_level')
    op.drop_column('collar_readings', 'acceleration_magnitude')
    # ### end Alembic commands ###
