"""Add TemperatureReading

Revision ID: 90fbed9f27c6
Revises: 39c92feb0679
Create Date: 2026-09-02 12:24:29.155566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fbed9f27c6'
down_revision: Union[str, Sequence[str], None] = '39c92feb0679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('cow_id', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperature_readings_id'), 'temperature_readings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temperature_readings_id'), table_name='temperature_readings')
    op.drop_table('temperature_readings')
    # ### end Alembic commands ###
