"""Initial migration

Revision ID: b61f560639ca
Revises: 
Create Date: 2026-09-01 23:23:46.921884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b61f560639ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collar_devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collar_devices_id'), 'collar_devices', ['id'], unique=False)
    op.create_index(op.f('ix_collar_devices_mac_address'), 'collar_devices', ['mac_address'], unique=True)
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_lat', sa.String(), nullable=True),
    sa.Column('location_long', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.create_table('smart_cups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smart_cups_id'), 'smart_cups', ['id'], unique=False)
    op.create_index(op.f('ix_smart_cups_mac_address'), 'smart_cups', ['mac_address'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('collar_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collar_id', sa.String(), nullable=False),
    sa.Column('activity_level', sa.String(), nullable=False),
    sa.Column('rumination_minutes', sa.Float(), nullable=False),
    sa.Column('body_temperature', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collar_id'], ['collar_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collar_readings_id'), 'collar_readings', ['id'], unique=False)
    op.create_table('cows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rfid', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('collar_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collar_id'], ['collar_devices.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cows_id'), 'cows', ['id'], unique=False)
    op.create_index(op.f('ix_cows_rfid'), 'cows', ['rfid'], unique=True)
    op.create_table('ai_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('days_to_onset', sa.Integer(), nullable=True),
    sa.Column('risk_factors', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_predictions_id'), 'ai_predictions', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('lab_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.String(), nullable=False),
    sa.Column('scc', sa.Integer(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('pathogen', sa.String(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_records_id'), 'lab_records', ['id'], unique=False)
    op.create_table('manual_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_data_id'), 'manual_data', ['id'], unique=False)
    op.create_table('milking_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cow_id', sa.String(), nullable=False),
    sa.Column('smart_cup_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['smart_cup_id'], ['smart_cups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milking_sessions_id'), 'milking_sessions', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('accuracy_rating', sa.Integer(), nullable=False),
    sa.Column('actual_outcome', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['ai_predictions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_table('milk_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('yield_volume', sa.Float(), nullable=False),
    sa.Column('ec', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('colour_score', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['milking_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milk_readings_id'), 'milk_readings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milk_readings_id'), table_name='milk_readings')
    op.drop_table('milk_readings')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_milking_sessions_id'), table_name='milking_sessions')
    op.drop_table('milking_sessions')
    op.drop_index(op.f('ix_manual_data_id'), table_name='manual_data')
    op.drop_table('manual_data')
    op.drop_index(op.f('ix_lab_records_id'), table_name='lab_records')
    op.drop_table('lab_records')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_ai_predictions_id'), table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index(op.f('ix_cows_rfid'), table_name='cows')
    op.drop_index(op.f('ix_cows_id'), table_name='cows')
    op.drop_table('cows')
    op.drop_index(op.f('ix_collar_readings_id'), table_name='collar_readings')
    op.drop_table('collar_readings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_smart_cups_mac_address'), table_name='smart_cups')
    op.drop_index(op.f('ix_smart_cups_id'), table_name='smart_cups')
    op.drop_table('smart_cups')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_collar_devices_mac_address'), table_name='collar_devices')
    op.drop_index(op.f('ix_collar_devices_id'), table_name='collar_devices')
    op.drop_table('collar_devices')
    # ### end Alembic commands ###
